feat:playlist component
2110336-2565-2/sec2-group10-demo-frontend pull request #25
Opened 2023-02-24 06:04 UTC by THrapooM

![image](https://user-images.githubusercontent.com/51509263/221104474-0f08b039-0dd4-40a6-9bab-57a4bfe069ff.png)

2023-02-24 06:17 UTC, NonKhuna requested changes
1. The color of subtitle 2 should be `text.secondary`
![image](https://user-images.githubusercontent.com/60351130/221105997-fe93b731-0e69-4dbc-bb98-41c463eeae2f.png)

2. The bgcolor and shadow are not the same as the design. Please fix it.
![image](https://user-images.githubusercontent.com/60351130/221106309-1dc001be-fc9c-4c10-8a0b-0c644722dec2.png)

2023-02-24 06:23 UTC, THrapooM commented
shadow on the image?

2023-02-24 06:24 UTC, NonKhuna commented
On The card component.

2023-02-24 06:26 UTC, THrapooM commented
I c . I interview pap

2023-02-24 06:27 UTC, NonKhuna commented
Good luck krub.

2023-02-25 15:24 UTC, NonKhuna approved these changes

2023-02-27 12:42 UTC, karnjj commented on src/components/Playlist.tsx
> +}
add `playlistId` to props to use when redirecting the page.

2023-02-28 06:00 UTC, merged